version: '3.4'
name: zmapl

networks:
  zmapl:
    driver: bridge

services:
  ZmapL_database:
    image: mysql
    container_name: ZmapL_database
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - zmapl
    volumes:
      - ./others/init.sql:/data/application/init.sql
      - ./others/mysql:/var/lib/mysql
    command: --init-file /data/application/init.sql
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 50M
