version: '3.4'
name: zmapl

networks:
  zmapl:
    driver: bridge

services:
  zmapldatabase:
    image: mysql
    container_name: zmapldatabase
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - zmapl
    volumes:
      - ./others/init.sql:/data/application/init.sql
      - ./others/mysql:/var/lib/mysql
    command: --init-file /data/application/init.sql
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 50M

  zmaplback:
    build: ./ZmapL-Back
    image: kmpc2013/zmaplback:v1
    container_name: zmaplback
    restart: on-failure
    environment:
      NODE_ENV: production
    ports:
      - 3333:3000
    networks:
      - zmapl
    depends_on:
      - "zmapldatabase"
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M
  
  # zmaplfront:
  #   build: ./ZmapL-Front
  #   image: kmpc2013/zmaplfront:v1
  #   container_name: zmaplfront
  #   restart: on-failure
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - 8081:80
  #   networks:
  #     - zmapl
  #   depends_on:
  #     - "zmaplback"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 100M
  #       reservations:
  #         memory: 50M
